import re

AOI_OP, AOI_NEXP, AOI_WEXP, AOI_STAT, AOI_BLOCK = 'OP', 'NEXP', 'WEXP', 'STAT',  'BLOCK'


AOI_NO = 'NO'
AOI_HIERARCHY = [AOI_OP, AOI_NEXP, AOI_WEXP, AOI_STAT, AOI_BLOCK]
COLOR_AOI_NAME_MAPPING = {
    (255, 0, 0):    AOI_OP,  # red
    (255, 160, 0):  AOI_NEXP,  # bright orange
    (255, 240, 0):  AOI_WEXP,  # bright yellow
    (0, 255, 0):    AOI_STAT,  # green
    (0, 0, 255):    AOI_BLOCK,  # blue
}

COLOR_AOI_NO = [0, 255, 255]

# POSITION MARKERS
POS_TOP = 'top'
POS_LEFT = 'left'
POS_BOTTOM = 'bottom'
POS_RIGHT = 'right'

CODE_AOI_PATTERN = re.compile('\[aoi=(\w*)\]')

AOI_SIZE = 'AoI_size'
AOI_PADDING = 5
AOI_PADDING_LARGE = {POS_BOTTOM: 15, POS_TOP: 15, POS_LEFT: 45, POS_RIGHT: 30}
AOI_PADDING_MEDIUM_LARGE = {POS_BOTTOM: 15,
                            POS_TOP: 15, POS_LEFT: 35, POS_RIGHT: 20}
AOI_PADDING_MEDIUM = {POS_BOTTOM: 15, POS_TOP: 15, POS_LEFT: 35, POS_RIGHT: 15}
AOI_PADDING_SMALL = {POS_BOTTOM: 15, POS_TOP: 15, POS_LEFT: 30, POS_RIGHT: 10}
AOI_PADDING_NO = {POS_BOTTOM: 0, POS_TOP: 15, POS_LEFT: 15, POS_RIGHT: 0}
