from utils.snippet_settings import CONDITION_CLEAN, CONDITION_CONFUSING
from utils.visual_settings import (
    FIXATION_SELECTION_ALGORITHM_FIRST_AOI_PADDING_SMALL)

EEG_FREQUENCY = 500
MNE_KEY_FREQUENCY = 'sfreq'


EOG_CHANNELS = ['VEOGP', 'VEOGM', 'HEOGP', 'HEOGM']
EEG_CHANNELS = ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FC5', 'FC3', 'FCz', 'FC4', 'FC6',
                'T7', 'C3', 'Cz', 'C4', 'T8', 'CP3', 'CPz', 'CP4', 'P7', 'P3', 'Pz', 'P4', 'P8', 'O1', 'O2']

IMPEDANCE_VALUE = 'imp'
IMPEDANCE_LOWER_BOUND = 'imp_lower_bound'
IMPEDANCE_UPPER_BOUND = 'imp_upper_bound'

# ICA files
ICA_REASONING_COLUMN_COMPONENT = 'Component'
ICA_REASONING_COLUMN_DESCRIPTION = 'Description'
ICA_REASONING_COLUMN_TOPOLOGY = 'Topology'
ICA_REASONING_COLUMN_RELATED = 'Artifact or Channel related'
ICA_REASONING_COLUMN_INCLUDED = 'Included'
ICA_REASONING_COLUMN_REASON = 'Reason'
ICA_REASONING_COLUMNS = [
    ICA_REASONING_COLUMN_COMPONENT, ICA_REASONING_COLUMN_DESCRIPTION,
    ICA_REASONING_COLUMN_TOPOLOGY, ICA_REASONING_COLUMN_RELATED,
    ICA_REASONING_COLUMN_INCLUDED, ICA_REASONING_COLUMN_REASON
]


ACCEPTED_SYNCHRONIZATION_OFFSET = 0.2

########
# EEG STIMULI
########
EEG_STIMULUS_FIXATION_CROSS = 'Stimulus/S  3'
EEG_STIMULUS_SNIPPET_END = 'Stimulus/S  4'

EEG_STIMULUS_SNIPPET_START = {
    CONDITION_CLEAN: 'Stimulus/S 11', CONDITION_CONFUSING: 'Stimulus/S 12'}

EEG_STIMULUS = ([EEG_STIMULUS_FIXATION_CROSS,
                EEG_STIMULUS_SNIPPET_END] +
                list(EEG_STIMULUS_SNIPPET_START.values()))

STIMULUS_EVENT_NAMES = {
    EEG_STIMULUS_FIXATION_CROSS: 'fixation_cross',
    EEG_STIMULUS_SNIPPET_END: 'end_stimuli',
    CONDITION_CLEAN: 'start_stimuli/clean/clarified',
    CONDITION_CONFUSING: 'start_stimuli/confusing/obfuscated'
}

########
# EEG Recording Buffer
########

EEG_SHORT_BUFFER = 1.0
EEG_MEAN_BUFFER = 6.0
EEG_LONG_BUFFER = 40.0


########
# EEG Voltage Step
########
EEG_VOLTAGE_STEP = 30
EEG_VOLTAGE_WINDOW = 100
EEG_VOLTAGE_OVERALL = [-70, 70]

#######
# ERP parameters
#######
EEG_MEAN_AMPLITUDE = 'Average_Amplitude'

ERP_PARAMETER_PARTICIPANTS = 'participants'
ERP_PARAMETER_ERP_FRP = 'erp_frp'
ERP_PARAMETER_CONDITIONAL_STIMULI = 'conditional_stimuli'
ERP_PARAMETER_PLOT = 'plot'
ERP_PARAMETER_EPOCH_INTERVAL = 'epoch_interval'
ERP_PARAMETER_CORRECT_TRIALS_ONLY = 'correct_data_only'
ERP_PARAMETER_TOPOMAP_TIMES = 'topomap_times'
ERP_PARAMETER_SNIPPET_GROUP = 'snippet_group'
ERP_PARAMETER_SNIPPET_NUMBERS = 'snippet_numbers'
ERP_PARAMETERS = [
    ERP_PARAMETER_PARTICIPANTS,
    ERP_PARAMETER_ERP_FRP,
    ERP_PARAMETER_CONDITIONAL_STIMULI,
    ERP_PARAMETER_PLOT,
    ERP_PARAMETER_EPOCH_INTERVAL,
    ERP_PARAMETER_CORRECT_TRIALS_ONLY,
    ERP_PARAMETER_TOPOMAP_TIMES,
    ERP_PARAMETER_SNIPPET_GROUP,
    ERP_PARAMETER_SNIPPET_NUMBERS
]


ERP_PERM_PARAMETER_CHANNEL_DESCRIPTION = 'channel_description'
ERP_PERM_PARAMETER_CHANNELS = 'channels'
ERP_PERM_PARAMETER_PERMUTATION_COUNT = 'permutation_count'
ERP_PERM_PARAMETER_CLUSTER_COUNT = 'cluster_count'
ERP_PERM_PARAMETER_POSITIVE_CLUSTER_COUNT = 'positive_cluster_count'
ERP_PERM_PARAMETER_POSITIVE_CLUSTERS = 'positive_clusters'
ERP_PERM_PARAMETER_NEGATIVE_CLUSTER_COUNT = 'negative_cluster_count'
ERP_PERM_PARAMETER_NEGATIVE_CLUSTERS = 'negative_clusters'
ERP_PERM_PARAMETER_SUBINTERVAL = 'subinterval'
ERP_PERM_PARAMETER_T_STATISTICS = 'T_statistics'
ERP_PERM_PARAMETER_H0 = 'H0'
ERP_PERM_PARAMETER_P_VALUES_CONFIDENT = 'p_values_confident'
ERP_PERM_PARAMETER_FREQUENCY = 'frequency'
ERP_PERM_PARAMETER_NEXT_P_VALUE = 'next_p_value'
ERP_PERM_PARAMETER_REQUIRED_PERMUTATION_COUNTS = 'required_permutation_counts'

ERP_PERM_CLUSTER_PARAMETER_P_VALUE = 'p_value'
ERP_PERM_CLUSTER_PARAMETER_TIMES = 'times'
ERP_PERM_CLUSTER_PARAMETER_CHANNELS = 'channels'
ERP_PERM_CLUSTER_PARAMETER_TIME_RANGE = 'time_range'
ERP_PERM_CLUSTER_PARAMETER_CHANNEL_RANGE = 'channel_range'
ERP_PERM_CLUSTER_PARAMETER_CLUSTER = 'cluster'


ERP_PERM_CHANNELS_TO_IGNORE = ['O1', 'O2', 'T7', 'T8']
#######
# FRP marker
#######
FRP_EEG_STIMULUS_SNIPPET_START = {
    FIXATION_SELECTION_ALGORITHM_FIRST_AOI_PADDING_SMALL: {CONDITION_CLEAN: 'Stimulus/S191', CONDITION_CONFUSING: 'Stimulus/S192'},
}

ERP_CLUSTER_ORIENTATION_INTEGER_CODING = {
    'Fp': 1,
    'F': 3,
    'FC': 4,
    'C': 5,
    'CP': 6,
    'P': 7,
    'O': 9,

    'z': 0,
    '1': -2,  # since only Fp has 1 and 2, and they align with the 3/4 row from other electrodes
    '2': +2,
    '3': -2,
    '4': +2,
    '5': -3,
    '6': +3,
    '7': -4,
    '8': +4}
