from scipy.stats import mannwhitneyu, ttest_ind, ttest_rel, wilcoxon

ALPHA = 0.05

MEAN = 'mean'
STD = 'std'

PVALUE = 'pvalue'

ALTERNATIVE_HYPOTHESIS = 'alternative hypothesis H1'
ALTERNATIVE_HYPOTHESIS_LESS = 'less'
ALTERNATIVE_HYPOTHESIS_GREATER = 'greater'
ALTERNATIVE_HYPOTHESIS_TWO = 'two-sided'
ALTERNATIVE_HYPOTHESES = [
    ALTERNATIVE_HYPOTHESIS_LESS, ALTERNATIVE_HYPOTHESIS_GREATER, ALTERNATIVE_HYPOTHESIS_TWO
]

STATISTIC_INFER_H1_ACCEPTED = 'H1 accepted'
STATISTIC_INFER_H1_NON_ACCEPTED = 'H0 kept, H1 not proven'

TEST = 'test'
TEST_WILCOXON = 'wilcoxon'
TEST_MANNWHITNEYU = 'mannwhitneyu'
TEST_T_PAIRED = 't-test paired'
TEST_T_INDEPENDENT = 't-test independent'

TEST_KIND_INDEPENDENT = 'independent'
TEST_KIND_PAIRED = 'paired'

TEST_KIND_PARAMETRIC = 'parametric'
TEST_KIND_NON_PARAMETRIC = 'non_parametric'

TEST = {TEST_KIND_PARAMETRIC: {
        TEST_KIND_PAIRED: TEST_T_PAIRED,
        TEST_KIND_INDEPENDENT: TEST_T_INDEPENDENT
        },
        TEST_KIND_NON_PARAMETRIC: {
        TEST_KIND_PAIRED: TEST_WILCOXON,
        TEST_KIND_INDEPENDENT: TEST_MANNWHITNEYU
        }
        }

TEST_FUNCTION = {
    TEST_WILCOXON: wilcoxon,
    TEST_MANNWHITNEYU: mannwhitneyu,
    TEST_T_PAIRED: ttest_rel,
    TEST_T_INDEPENDENT: ttest_ind
}

MEASURE = 'measure'


PERMUTATION_COUNT = 1e4
PERMUTATION_COUNT_START = 1e3
PERMUTATION_COUNT_MAX = 1e20
PERMUTATION_MAX_STEP_FREQUENCY_FACTOR = 0.01
PERMUTATION_CONFIDENCE_INTERVAL = 0.99

PERMUTATION_TEST_PARAMETERS = {TEST_KIND_PAIRED: {
    # ALTERNATIVE_HYPOTHESIS_TWO: {'tail': 0},
    ALTERNATIVE_HYPOTHESIS_GREATER: {'tail': 1},
    ALTERNATIVE_HYPOTHESIS_LESS: {'tail': -1},
}, TEST_KIND_INDEPENDENT: {
    ALTERNATIVE_HYPOTHESIS_GREATER: {'tail': 1},
    ALTERNATIVE_HYPOTHESIS_LESS: {'tail': 1},
}}


PERMUTATION_TEST_COLORS = {
    ALTERNATIVE_HYPOTHESIS_TWO: 'g',
    ALTERNATIVE_HYPOTHESIS_GREATER: 'y',
    ALTERNATIVE_HYPOTHESIS_LESS: 'c',
}

PERMUTATION_PLOT_PIXEL_Y, PERMUTATION_PLOT_PIXEL_X = 16, 10

EFFECT_STRENGTH_NEGLIGIBLE = 'negligible'
EFFECT_STRENGTH_SMALL = 'small'
EFFECT_STRENGTH_MEDIUM = 'medium'
EFFECT_STRENGTH_LARGE = 'large'
EFFECT_STRENGTHS = [EFFECT_STRENGTH_NEGLIGIBLE, EFFECT_STRENGTH_SMALL,
                    EFFECT_STRENGTH_MEDIUM, EFFECT_STRENGTH_LARGE]
